---
- hosts: odoo
  become: true
  tasks:
    - name: Installer aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Installer les packages pour docker
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Ajouter la clé GPG apt
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Ajout du repo docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: apt update et installation de docker
      apt:
        name: docker-ce
        state: latest
        update_cache: true
